# Site settings
title: 叙事学派
email: 
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jude90.github.io" # the base hostname & protocol for your site
twitter_username: ""
github_username:  jude90

# Build settings
# markdown: kramdown
markdown: redcarpet
highlighter: pygments
highlight: true

# markdown: kramdown
# kramdown:
#   input: GFM          
paginate: 8
paginate_path: "/blog/page:num"

# paginate_path: "page:num"

gems: [jekyll-paginate]